In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 1. DIMENSION IN ARRAY

In [11]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1D ARRAY

In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


# 2D ARRAY

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


# 3D ARRAY

In [15]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


# check number of dimensions

In [16]:
import numpy as np

arr1 = np.array(40)
arr2 = np.array([1,2,3])
arr3 = np.array([[[1,2,3],[4,5,6]]])
arr4 = np.array([[[[1,2,3],[1,2,3],[1,2,3]]]]) 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
3
4


# Create an array with 5 dimensions and verify that it has 5 dimensions 

In [18]:
import numpy as np 

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


# OR

In [22]:
# arr = np.array([[[[[1,2,3,4,5]]]]])
print(arr)
print('number of dimension : ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension :  5


# NumPy array indexing

In [ ]:
Array indexing is the same as accesing an array element
You can access an array element by referring to its index number
The indexes in NumpY arrays starts with 0, meaning that the first elements has index 0, and the second has index 1 etc

# Get the first element from the following array :

In [23]:
arr = np.array([1,2,3,4])
print(arr[0])

1


# Get third and sixth and 8th elements from the following array and add them

In [24]:
m = np.array([1,2,3,4,5,6,7,8,9,10])
print("The third element is : ", m[2])
print("The sixth element is : ", m[6])
print("The eight element is : ", m[8])
print("sum of this element are ", m[2]+m[6]+m[8])


The third element is :  3
The sixth element is :  7
The eight element is :  9
sum of this element are  19


# TO access elements from 2D arrays

In [25]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("2nd element on 1st row", arr[0,1])

2nd element on 1st row 20


In [26]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("4TH element on 1st row", arr[0,3])

4TH element on 1st row 40


In [29]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("5th element on 2nd row", arr[1,4])

5th element on 2nd row 100


# Add the first element of row 1 and last element

In [34]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("first element of row1", arr[0,0])
print("last element of row2", arr[1,4])
print("sum of row1 and row2 is ", arr[0,0]+arr[1,4])

first element of row1 10
last element of row2 100
sum of row1 and row2 is  110


# To access 3-D arrays

# Access the third element of the second array of the first array

In [39]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [40]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,3,2])

12
